Avoid a race condition when creating LOG_DIR (#2281)
One of the Fedora Linux users had this traceback reported automatically:

    Traceback (most recent call last):
      File "/usr/bin/mu-editor", line 8, in <module>
        sys.exit(run())
      File "/usr/lib/python3.10/site-packages/mu/app.py", line 111, in run
        setup_logging()
      File "/usr/lib/python3.10/site-packages/mu/app.py", line 47, in setup_logging
        os.makedirs(LOG_DIR)
      File "/usr/lib64/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/home/robertfairbrother/.cache/mu/log'

Looking at the code, this can probably happen when Mu is started twice
at the same time. Instead of checking if the dir exist, just attempt to create
it and don't fail if it is already there.